
## Links
## http://plugins.drone.io/drone-plugins/drone-github-release/

kind: pipeline
name: default

workspace:
  base: /build
#  path: src/github.com/yourname/go-drone-hello-world

steps:
  - name: build-xenial
    image: ubuntu:xenial
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - pwd
      - ls -ilah
      - ls /
      - cd scripts
      - bash NVENC-FFMPEG-OBSbuild.sh --dest /opt/ffmpeg-obs
      - mkdir -p /build/dist/
      - mv /root/dist/ffmpeg-obs-nvenc_* /build/dist/
    when:
      event: master

      
  - name: build-bionic
    image: ubuntu:bionic
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - cd scripts
      - bash NVENC-FFMPEG-OBSbuild.sh --dest /opt/ffmpeg-obs
      - mkdir -p /build/dist/
      - mv /root/dist/ffmpeg-obs-nvenc_* /build/dist/
    when:
      event: master2


  - name: build-disco
    image: ubuntu:disco
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - cd scripts
      - bash NVENC-FFMPEG-OBSbuild.sh --dest /opt/ffmpeg-obs
      - mkdir -p /build/dist/
      - mv /root/dist/ffmpeg-obs-nvenc_* /build/dist/
    when:
      event: master2


  - name: publish
    image: plugins/github-release
    settings:
      api_key: $GITHUB_API_KEY
      files: 
        - dist/*
      checksum:
        - md5
        - sha1